#spring:
#  datasource:
#    url :  jdbc:mysql://localhost/test
#    username : root
#    password : root
#    driver-class-name: com.mysql.jdbc.Driver
#  jpa:
#    show-sql :  false
#    hibernate.ddl-auto: update

#spring.jackson.serialization.fail-on-empty-beans: false

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver