spring:
  datasource:
    url :  jdbc:mysql://localhost/test
    username : root
    password : root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql :  true
    hibernate.ddl-auto: update

#spring.jackson.serialization.fail-on-empty-beans: false
